name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux-intel:
    strategy:
      matrix:
        docker_image: ['realnc/hugor-build:linux-x86', 'realnc/hugor-build:linux-x64']

    runs-on: ubuntu-latest
    container: ${{ matrix.docker_image }}

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        qmake
        make appimage

  trigger-circleci-arm:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger CircleCI ARM builds
      id: 'build-linux-arm'
      uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
      env:
        CCI_TOKEN: ${{ secrets.CCI_TOKEN }}

  build-mxe:
    runs-on: ubuntu-latest
    container: 'realnc/hugor-build:mxe-x86'

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        i686-w64-mingw32.static-qmake-qt5
        make windist

  build-macos:
    runs-on: macos-10.15
    env:
      HOMEBREW_PREFIX: /Users/Shared/homebrew-qtads-hugor
      HOMEBREW_CELLAR: /Users/Shared/homebrew-qtads-hugor/Cellar
      HOMEBREW_SHELLENV_PREFIX: /Users/Shared/homebrew-qtads-hugor
      PKG_CONFIG_PATH: /Users/Shared/homebrew-qtads-hugor/opt/readline/lib/pkgconfig

    steps:
    - run: echo "${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:${PATH}" >> $GITHUB_PATH

    - name: Install custom homebrew
      run: |
        rm -rf "${HOMEBREW_PREFIX}"
        mkdir "${HOMEBREW_PREFIX}"
        cd "${HOMEBREW_PREFIX}"/..
        curl -s -S -L 'https://github.com/realnc/stuff/releases/download/stuff/homebrew-qtads-hugor.tar.zst' | zstd -d | tar x

    - name: Remove /usr/local homebrew
      working-directory: /usr/local
      run: |
        sudo mkdir ~/oldbrew
        sudo mv * ~/oldbrew/

    - name: Download VLC
      working-directory: /usr/local
      run: |
        curl -s -S -L 'https://github.com/realnc/stuff/releases/download/stuff/vlc-3.0.16-macos.tar.zst' | zstd -d | sudo tar x

    - name: Download Qt
      working-directory: /opt
      run: |
        curl -s -S -L 'https://github.com/realnc/stuff/releases/download/stuff/qt-5.15-macos-static.tar.zst' | zstd -d | sudo tar x

    - name: Enable 10.15 SDK
      run: |
        sudo mv \
          "/Applications/Xcode_12.1.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" \
          "`xcode-select -p`/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk"

    - uses: actions/checkout@v2

    - name: Build
      run: |
        /opt/qt-5.15/bin/qmake -after CONFIG-=silent
        make macdist

    - name: Restore /usr/local homebrew
      working-directory: /usr/local
      run: |
        sudo rm -rf *
        sudo mv ~/oldbrew/* .
